language: node_js
node_js:
#  - "7"
#  - "6"
  - "6.8"
  - "6.7"
  - "6.6"
  - "6.5"
  - "6.4"
  - "6.3"
os:
  - linux
  #- osx
env:
  global:
    - secure: Rov9tYDaMYPBUeWDtD43S9h3llaljjMB0Khdi7P+kbkYOUPCm+Ol1Sr7nS+lwOQpF/3T1kva2OQ/LWkOM8kSng86EkMviEGQXpdlGRxP9clo8qmxyfbcKID5Q/a29kOIbkbbhx9cGFoepEjo+5T+Ya7GbbXIyMt1PNTCy5eLXnfU8BE/G3Ib8eVNBxGANiOuBTkKfzTyajH+pcsj0Wvr2Po/PjSIwYk6EfCzsYWbLDxjo86w7hD7F5OtjxPJTsYz3K1OwdneaUJ3bYLrGqpNewIfR4gASNTB4fBio0ZdBZ44UulKo6rO7tUMMQdCGm9+c54XeVGigJE9uhz8Fcim3FpfY9jraT9dhp5xPgvDl0OC/NVvHAGumak67X4Vkui5dAGGqbfNGfnWRvzkar/Xj3QpO7UJ0VEp2nFmZqgwE9CHhi+xMAh2+C5aoVsvtdb8LiACnN0YOfrMQvkoX2JGoGrLuJGJSTC3fRiLFIvWnX73L7+XKlrRUceoroyQ6WXEPkUbrtVtTN/yE0CVJmpVS1oE4Nre3zvOQAtIxGJWbk2rYTQ95C7cixAeo7ucFnX3J6YrSiTm0Ny+smdgv2KkXX8Q+UY0JG10BN3tHc67gqpvsaAPQaPGq4KF/jngE4a5H+skzpTnPRU0sozY4uNDXwGZmo4va03NFk6XVMk9rzo= # CODECLIMATE
    - secure: EtPvv9j3yZ8UjlloTx/5UIeRTIc4lSBirjhEKrOEDz5AVTBy71ndwOPo/pOg9sG6NclaXOZpYeVxw5LtsoX9fNW7fQZzkkENfYK7S0TgNrcAYfoAdkvV7IdjU0UkQG7hzSqT14Ad+//trfA/ExERHP/yQ6UhJ/wZRx/z4jQORgC/CtoB9nPugO04Wl+nzL9hS68Eh6NdVwEBNVNDjaNgpONfes8n5cNsGK90O9IVwGqleLsJ+nk3ZIit4zWHNkyxN22an0s8Cql/l+WlQlr2LlJG1iYVFyQALVqgcSOn3LQBDWW2FDEFZO40zKPKwvymTFezP+UAOupBtHTWnF2he5fNgPDYpc27QyKrxp7yfKFRtwSlAY2ONTNtzQ/eJmuSF8QKDm5oh9za9+SnxRlbNhG0hcYtIBjYVp2E8ocVqLd2LWanfFDbUI5Qij6aZTyRXsHGqgY6gpAo6zAToOfSXCxFXW8Y9p4KQszcxSenvCHxn9H08A8HJipsN3PJAHex/ZD4Kw6SzerC0XKvnhhg2jmasamjlLy4mlY4xlIkGns7PF+3818nlw9Naans83+fB8ngy+GbHC1vOoKO0QzE0ZorEFEt9t6wADFdOnZvFZ09MHz90bOUryUC6OT2JO44t9ES66oLE+8e9yheCgKyTpnEHgfvSaOGqEmzMGoCTgY= # COVERALLS
before_install:
  - bash travisci/before_install.sh
sudo: required
addons:
  firefox: latest
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - bash travisci/travis_script.sh
after_success:
  - bash travisci/after_success.sh
branches:
  only: master
cache:
  apt: true
  bundler: true
  directories:
    - node_modules